after_success: coveralls
cache: pip
dist: xenial
install: pip install black coveralls flake8 pydocstyle
language: python
matrix:
  fast_finish: true
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
script:
  - black --check -l 79 *.py examples prawcore tests
  - flake8
  - pydocstyle
  - coverage run --source=prawcore setup.py test
