cache: pip
dist: xenial
install: pip install coveralls
jobs:
  include:
    - install: pip install black flake8 pydocstyle
      python: 3.7
      script:
        - black --check --verbose *.py examples prawcore tests
        - flake8
        - pydocstyle
      stage: lint
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
script:
  - coverage run --source=prawcore setup.py test
  - coveralls
stages:
  - lint
  - test
